spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fortic5
    username: web
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql