spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fortic5
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  security:
    user:
      name: remunata
      password: qwerty123